opam-version: "2.0"

synopsis:"A simple OCaml REST API"
description: "A simple OCaml REST API server using cohttp that returns a list of users and books"

license: "MIT"
homepage: "https://github.com/dinakajoy/simple_ocaml_rest_api_server"
bug-reports: "https://github.com/dinakajoy/simple_ocaml_rest_api_server/issues"

author: "Odinaka Joy <dinakajoy@gmail.com>"
maintainer: "Odinaka Joy <dinakajoy@gmail.com>"

depends: [
  "dune"
  "ocaml" {>= "5.4.0"}
  "yojson"
  "cohttp-lwt-unix"
  "lwt"
]
